### ISSUE TITLE
bt-luaengine makefile doesn't work on 64-bit linux, skybox.obj is missing

### ISSUE THREAD

**Issue by unity-car-tutorials** [robdoesstuff/batterytech#2]
I'm using Ubuntu 14.04 64-bit, with GCC 4.8.2. The **-pthread** option was needed for both CXXFLAGS and CFLAGS, and **-lpthreads** to LINKED_LIBS for it to compile, but the Lua demo doesn't seem to work, since it can't find all of the assets, specifically skybox.obj.

**Comment by robdoesstuff** [comment]
Sorry, those were excluded by default in the gitignore.  I added them now and pushed to release-2.0.  Try that out.  Feel free to make a branch and PR for the build config update for 64 bit ubuntu and I'll review it.
